name:               "Julien Blanchard"

author:
  twitter:          julienXX
  github:           julienXX
  linkedin:         blanchardjulien
  email:            me@julienblanchard.com

copyright:
  year:             2017
  name:             Julien Blanchard

# Google-analytics
google-analytics:
  id:               "UA-9345972-3"

# URL
url:                "http://julienblanchard.com"
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Paris
permalink:          /:year/:title/

# Pagination
paginate:           3
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/julienXX"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate

exclude:            [vendor]
