name: Julien Blanchard
description: Software Plumber
meta_description: "Julien Blanchard"

aboutPage: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://julienblanchard.com'
google_analytics: 'UA-9345972-3'
disqus_shortname: 'julienblanchard'

# Details for the RSS feed generator
url:            'http://julienblanchard.com'
author:         'Julien Blanchard'
authorTwitter:  'julienXX'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
